package com.utmir.raptornet.models;

public enum ERole {
  
  ROLE_ASPIRANTE,
  ROLE_ALUMNO,
  ROLE_BAJA_DEFINITIVA,
  ROLE_BAJA_TEMPORAL,
  ROLE_BAJA_ABANDONO,
  ROLE_NO_CONTINUIDAD,
  ROLE_INACTIVO_FALTA_PAGO,
  ROLE_EGRESADO_TSU,
  ROLE_EGRESADO_ING_LIC,
  ROLE_VINCULACION,
  ROLE_FINANZAS,
  ROLE_SERVICIOSESCOLARES,
  ROLE_DIRECCION_ACADEMICA,
  ROLE_DOCENTES,
  ROLE_ADMIN
}
